services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
    volumes:
      - ./init_scripts:/docker-entrypoint-initdb.d
    ports:
      - "23210:5432"