version: "3.9"
services:
  postgres:
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "keycloakdb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
    ports:
      - "23210:5432"
    networks:
      - keycloak-network

  keycloak:
#    image: quay.io/keycloak/keycloak:22.0.5
    image: jboss/keycloak:16.1.1
    ports:
      - 8180:8080
    environment:
      KEYCLOAK_ADMIN: "admin"          # Администратор Keycloak
      KEYCLOAK_ADMIN_PASSWORD: "admin" # Пароль администратора Keycloak

      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloakdb
      DB_SCHEMA: public
      DB_USER: keycloakuser
      DB_PASSWORD: keycloakpass

#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: adminpass
    networks:
      - keycloak-network
    depends_on:
      - postgres
    command: ["start-dev"]

networks:
  keycloak-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local