spring:
  application:
    name: FirstLab

  datasource:
    url: jdbc:postgresql://localhost:23210/habrdb
    username: user
    password: user

  jpa:
    show-sql: true
    properties:
      javax:
        persistence:
          provider: org.eclipse.persistence.jpa.PersistenceProvider
      eclipse:
        link:
          logging:
            level: FINE
            file: stdout
    hibernate:
      ddl-auto: create

server:
  error:
    whitelabel:
      enabled: false

  web:
    resources:
      add-mappings: false