spring:
  application:
    name: FirstLab

  datasource:
#    todo здесь менять на jdbc:postgresql://postgresql:5432/first при запуске с докера
    url: jdbc:postgresql://localhost:5432/first
    username: user
    password: user

  jpa:
    show-sql: true
    properties:
      javax:
        persistence:
          provider: org.eclipse.persistence.jpa.PersistenceProvider
      eclipse:
        link:
          logging:
            level: FINE
            file: stdout
    hibernate:
      ddl-auto: update

server:
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false


token:
  signing:
    key: Q5v1CXQ1Y64cayU84BnlR3Az9fVFe8Bvn6Mrf68bX5U=
  salt:
    PBKDF2WithHmacSHA1