name: Lint Code Base

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['**']

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
#          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVA: true
#          ACTIONS_RUNNER_DEBUG: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          LINTER_RULES_PATH: .github/linters/sun_checks.xml

      - name: Debug Linter
        run: cat .github/linters/sun_checks.xml

      - name: Run Checkstyle wat
        run: |
          java -jar checkstyle.jar -c .github/linters/checkstyle.xml src/main/java/